name: Build and Test ROS2 Package on Multiple Versions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distribution: [humble, iron]

    steps:
    - name: リポジトリのコードを取得
      uses: actions/checkout@v3

    - name: ROS2環境のセットアップ
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}

    - name: 依存関係のインストール
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ros-${{ matrix.ros_distribution }}-ament-cmake \
          ros-${{ matrix.ros_distribution }}-rclcpp \
          ros-${{ matrix.ros_distribution }}-std-msgs

    - name: 環境変数の設定
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.bash

    - name: ビルドキャッシュのクリア
      run: |
        rm -rf build install log

    - name: ビルドの実行
      run: |
        colcon build --packages-select hello_pkg

    - name: テストの実行
      run: |
        source install/setup.bash
        ros2 run hello_pkg hello &
        sleep 10
        ros2 topic echo /current_time --once
